### ISSUE TITLE
cuda error of neural_renderer

### ISSUE THREAD

**Issue by xhuan8** [akashsengupta1997/STRAPS-3DHumanShapePose#15]
hi,

there is a cuda error for neural_renderer, I cannot figure out how to fix it.
the file 'libcudart.so.10.1' link to '/usr/local/cuda-10.0/lib64/libaccinj64.so.10.0.130'
but don't understand why neural_renderer uses libcudart.so.10.1

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiehuan/anaconda3/lib/python3.8/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/xiehuan/anaconda3/lib/python3.8/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /usr/lib/libcudart.so.10.1: version `libcudart.so.10.1' not found (required by /home/xiehuan/anaconda3/lib/python3.8/site-packages/neural_renderer/cuda/load_textures.cpython-38-x86_64-linux-gnu.so)

**Comment by xhuan8** [comment]
only difference is i install cuda toolkit 10.0 to let detectron to work

**Comment by xhuan8** [comment]
fixed by run: pip3 install git+https://github.com/daniilidis-group/neural_renderer/
